---
alerting:
  alertmanagers:
    -
      static_configs:
        -
          targets:
            - "alertmanager:9093"
global:
  evaluation_interval: 10s
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - prometheus:9090
  - job_name: grafana
    static_configs:
    - targets:
      - grafana:3000